# Generated by Django 6.0.4 on 2026-05-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_badge_product_bg_color_product_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text='FontAwesome icon class (e.g., fa-solid fa-bed)', max_length=50, null=True),
        ),
    ]
