# Generated by Django 6.0.4 on 2026-05-04 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
