# Generated by Django 6.0.4 on 2026-05-06 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_category_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount_percent',
        ),
        migrations.RemoveField(
            model_name='product',
            name='old_price',
        ),
    ]
