# Generated by Django 6.0.4 on 2026-05-10 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_discount_percent_product_old_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount_percent',
        ),
        migrations.RemoveField(
            model_name='product',
            name='old_price',
        ),
    ]
